swagger: '2.0'
info:
  description: Provieds raw home data.
  version: 1.0.0
  title: Home-Log
  contact: { name: 'veasy' }
tags:
  - name: DATA
    description: Read data form the service.
consumes:
  - application/json
produces:
  - application/json

paths:
  /meteo/temperature:
    get:
      description: Get raw temperature json data.
      tags:
        - DATA
      operationId: homelog.routes.log_route.get_temperature
      parameters:
        - $ref: "#/parameters/startTime"
        - $ref: "#/parameters/endTime"
      responses:
        200:
          description: OK


  /meteo/pressure:
    get:
      description: Get raw pressure json data.
      tags:
        - DATA
      operationId: homelog.routes.log_route.get_pressure
      parameters:
        - $ref: "#/parameters/startTime"
        - $ref: "#/parameters/endTime"
      responses:
        200:
          description: OK

  /meteo/humidity:
    get:
      description: Get raw humidity json data.
      tags:
        - DATA
      operationId: homelog.routes.log_route.get_humidity
      parameters:
        - $ref: "#/parameters/startTime"
        - $ref: "#/parameters/endTime"
      responses:
        200:
          description: OK

  /data/raw:
    post:
      description: Post raw data to the service.
      tags:
        - DATA
      operationId: homelog.routes.log_route.post_raw
      responses:
        200:
          description: OK

parameters:
  startTime:
    name: startTime
    in: query
    description: Start time of dataset.
    required: true
    type: string
    format: date-time

  endTime:
    name: endTime
    in: query
    description: End time of dataset.
    required: true
    type: string
    format: date-time